name: Test

on:
  push:
  pull_request:

jobs:
  cppro-protocol:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run CPPRO tests
        shell: powershell
        run: .\tools\run_tests.ps1
